/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SFQkPJ3ecSt
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
} from "@/components/ui/carousel";
import { Card, CardContent } from "@/components/ui/card";
import Header from "../layout/header";
import BestSellers from "./bestSellers";
import OneCategory from "./oneFlower";
import ShopByOccasion from "./shopByOccasion";

export function HomePage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <img
        src="/placeholder.svg"
        alt="Flower Carousel 1"
        width={1920}
        height={1080}
        className="object-cover w-full h-96"
      />
      <div className="bg-muted py-4 md:py-6 lg:py-8">
        <div className="container justify-around flex grid-cols-1 md:grid-cols-3 gap-4 md:gap-6 lg:gap-8">
          <div className="flex items-center gap-2 md:gap-3">
            <TruckIcon className="w-6 h-6 md:w-8 md:h-8" />
            <div>
              <h3 className="text-sm md:text-base font-medium">
                Free Delivery
              </h3>
              <p className="text-xs md:text-sm text-muted-foreground">
                On all orders over $50
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 md:gap-3">
            <LockIcon className="w-6 h-6 md:w-8 md:h-8" />
            <div>
              <h3 className="text-sm md:text-base font-medium">Safe Payment</h3>
              <p className="text-xs md:text-sm text-muted-foreground">
                Secure checkout with SSL encryption
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 md:gap-3">
            <UsersIcon className="w-6 h-6 md:w-8 md:h-8" />
            <div>
              <h3 className="text-sm md:text-base font-medium">
                Friendly Service
              </h3>
              <p className="text-xs md:text-sm text-muted-foreground">
                Dedicated customer support
              </p>
            </div>
          </div>
        </div>
      </div>
      <BestSellers />
      <OneCategory />
      <ShopByOccasion/>
    </div>
  );
}

function LockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  );
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function TruckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />
      <path d="M15 18H9" />
      <path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" />
      <circle cx="17" cy="18" r="2" />
      <circle cx="7" cy="18" r="2" />
    </svg>
  );
}

function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  );
}
