/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4bx645zWbOl
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function About() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <section className="relative w-full h-[60vh] bg-[url('https://images.unsplash.com/photo-1586704235550-c4267ca3e6e9?fm=jpg&w=3000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGZsb3dlciUyMHNob3B8ZW58MHx8MHx8fDA%3D')] bg-cover bg-center bg-no-repeat one-category">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-muted/50" />
        <div className="relative h-full flex flex-col items-center justify-center px-4 text-center one-category">
          <h1 className="text-4xl sm:text-6xl font-bold text-primary-foreground">
            Blooming Blossoms
          </h1>
          <p className="max-w-[600px] mt-4 text-lg text-primary-foreground">
            Delivering the freshest and most beautiful flowers to your doorstep.
          </p>
        </div>
      </section>
      <section className="p-4 py-12 md:py-20 lg:py-28">
        <div className="container px-4 md:px-6 grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 lg:gap-16">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter text-center sm:text-4xl md:text-5xl">
              Our Mission
            </h2>
            <div className="bg-muted rounded-lg p-6">
              <p className="text-muted-foreground md:text-xl">
                At Blooming Blossoms, our mission is to bring joy and beauty
                into people's lives through the power of flowers. We are
                dedicated to sourcing the finest, freshest blooms and delivering
                them with the utmost care and attention to detail.
              </p>
            </div>
          </div>
          <div className="flex justify-center">
            <img
              src="https://media.istockphoto.com/id/1437870284/photo/young-beautiful-hispanic-woman-florist-make-bouquet-of-flowers-at-flower-shop.webp?b=1&s=170667a&w=0&k=20&c=1XzTArUzGPdd8iNEP1vhCLTO-TAQtTAd7Qjrr-8gQhQ="
              width={500}
              height={400}
              alt="Mission"
              className="rounded-lg shadow-lg card-style"
            />
          </div>
        </div>
      </section>
      <section className="py-12 md:py-20 lg:py-28 bg-muted">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Meet the Team
            </h2>
            <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl">
              Our passionate team of floral experts is dedicated to bringing you
              the best possible experience.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 mt-8">
            <div className="flex flex-col items-center space-y-4">
              <div className="rounded-full w-32 h-32 bg-muted flex items-center justify-center">
                <img
                  src="https://www.shutterstock.com/image-photo/headshot-portrait-smiling-african-american-260nw-1667439898.jpg"
                  width="200"
                  height="200"
                  alt="Emily Johnson"
                  className="rounded-full div-style  w-full h-full"
                />
              </div>
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Emily Johnson</h3>
                <p className="text-muted-foreground">
                  Co-Founder, Head Florist
                </p>
                <p className="text-muted-foreground">
                  Emily is a passionate floral designer with over a decade of
                  experience. She is dedicated to creating unique and visually
                  stunning arrangements.
                </p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <div className="rounded-full w-32 h-32 bg-muted flex items-center justify-center">
                <img
                  src="https://media.istockphoto.com/id/1300512215/photo/headshot-portrait-of-smiling-ethnic-businessman-in-office.jpg?s=612x612&w=0&k=20&c=QjebAlXBgee05B3rcLDAtOaMtmdLjtZ5Yg9IJoiy-VY="
                  width="200"
                  height="200"
                  alt="Emily Johnson"
                  className="rounded-full div-style  w-full h-full"
                />
              </div>
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Michael Lee</h3>
                <p className="text-muted-foreground">Co-Founder, Operations</p>
                <p className="text-muted-foreground">
                  Michael oversees the logistics and operations of Blooming
                  Blossoms, ensuring timely and reliable delivery of our
                  flowers.
                </p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <div className="rounded-full w-32 h-32 bg-muted flex items-center justify-center">
                <img
                  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHfHsJ0gRyl8LGr5W-V-dq3jKf-iUoOynafQ&s"
                  width="200"
                  height="200"
                  alt="Emily Johnson"
                  className="rounded-full div-style w-full h-full"
                />
              </div>
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Sarah Williams</h3>
                <p className="text-muted-foreground">
                  Head of Customer Experience
                </p>
                <p className="text-muted-foreground">
                  Sarah is dedicated to providing exceptional customer service
                  and ensuring every customer is delighted with their Blooming
                  Blossoms experience.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
