/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bJxPBvrARA1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Judson } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"

export function HomePage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 shadow">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-2xl font-bold" prefetch={false}>
            Bloom Boutique
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link href="#" className="hover:underline" prefetch={false}>
              Roses
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Lilies
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Orchids
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              About
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Link href="#" className="relative" prefetch={false}>
              <ShoppingCartIcon className="w-6 h-6" />
              <span className="absolute -top-2 -right-2 bg-accent text-accent-foreground rounded-full px-2 py-1 text-xs font-medium">
                3
              </span>
            </Link>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="rounded-full">
                  <img src="/placeholder.svg" width="32" height="32" className="rounded-full" alt="Avatar" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>My Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <Link href="#" prefetch={false}>
                    Account Settings
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" prefetch={false}>
                    Order History
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <h1 className="text-4xl font-bold mb-8">Discover Our Flowers</h1>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
              <div className="bg-background rounded-lg shadow-lg overflow-hidden">
                <img src="/placeholder.svg" width={400} height={400} alt="Rose" className="w-full h-64 object-cover" />
                <div className="p-4">
                  <h3 className="text-xl font-bold mb-2">Red Roses</h3>
                  <p className="text-muted-foreground mb-4">Vibrant red roses, perfect for any occasion.</p>
                  <div className="flex items-center justify-between">
                    <span className="text-2xl font-bold">$49.99</span>
                    <Button>Add to Cart</Button>
                  </div>
                </div>
              </div>
              <div className="bg-background rounded-lg shadow-lg overflow-hidden">
                <img src="/placeholder.svg" width={400} height={400} alt="Lily" className="w-full h-64 object-cover" />
                <div className="p-4">
                  <h3 className="text-xl font-bold mb-2">White Lilies</h3>
                  <p className="text-muted-foreground mb-4">Elegant and fragrant white lilies.</p>
                  <div className="flex items-center justify-between">
                    <span className="text-2xl font-bold">$39.99</span>
                    <Button>Add to Cart</Button>
                  </div>
                </div>
              </div>
              <div className="bg-background rounded-lg shadow-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={400}
                  alt="Orchid"
                  className="w-full h-64 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-xl font-bold mb-2">Purple Orchids</h3>
                  <p className="text-muted-foreground mb-4">Exotic and captivating purple orchids.</p>
                  <div className="flex items-center justify-between">
                    <span className="text-2xl font-bold">$59.99</span>
                    <Button>Add to Cart</Button>
                  </div>
                </div>
              </div>
              <div className="bg-background rounded-lg shadow-lg overflow-hidden">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={400}
                  alt="Bouquet"
                  className="w-full h-64 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-xl font-bold mb-2">Flower Bouquet</h3>
                  <p className="text-muted-foreground mb-4">A beautiful assortment of seasonal flowers.</p>
                  <div className="flex items-center justify-between">
                    <span className="text-2xl font-bold">$79.99</span>
                    <Button>Add to Cart</Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6">
        <div className="container mx-auto px-4 md:px-6 flex items-center justify-between">
          <p>&copy; 2023 Bloom Boutique. All rights reserved.</p>
          <nav className="flex items-center space-x-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Terms of Service
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}
